name: AI4Good
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - fonttools=4.57.0
  - freetype=2.13.3
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.4
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libexpat=2.7.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.4
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.3
  - python=3.11.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - readline=8.2
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - six=1.17.0
  - sqlite=3.45.2
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.21.0
      - confection==0.1.5
      - conllu==6.0.0
      - cymem==2.0.11
      - en-core-sci-sm==0.5.1
      - en-core-web-sm==3.4.1
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - murmurhash==1.0.12
      - nmslib-metabrainz==2.1.3
      - numpy==1.26.4
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - preshed==3.0.9
      - pybind11==2.13.6
      - pydantic==1.10.21
      - pydantic-core==2.33.1
      - pysbd==0.3.4
      - requests==2.32.3
      - rich==14.0.0
      - scikit-learn==1.6.1
      - setuptools==79.0.0
      - shellingham==1.5.4
      - smart-open==6.4.0
      - spacy==3.4.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - thinc==8.1.12
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typer==0.7.0
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - wasabi==0.10.1
      - weasel==0.4.1
      - wrapt==1.17.2
